<?php include 'includes/config.php'; require_role('seller'); $u=current_user();
$stmt=$pdo->prepare('SELECT * FROM brands WHERE seller_id=?');$stmt->execute([$u['id']]);$brand=$stmt->fetch(PDO::FETCH_ASSOC); if(!$brand) die('Create your brand first. <a href="create-brand.php">Create Brand</a>');
if($_SERVER['REQUEST_METHOD']==='POST'){
 $count=$pdo->prepare('SELECT COUNT(*) FROM product_images pi JOIN products p ON pi.product_id=p.id WHERE p.seller_id=?');$count->execute([$u['id']]); if($count->fetchColumn()>=MAX_TOTAL_IMAGES_PER_SELLER) die('Upload limit reached.');
 $name=clean($_POST['product_name']);$cat=clean($_POST['category']);$price=(float)$_POST['price'];$stock=(int)$_POST['stock'];$desc=clean($_POST['description']);
 $pdo->prepare('INSERT INTO products(brand_id,seller_id,product_name,category,price,stock,description) VALUES(?,?,?,?,?,?,?)')->execute([$brand['id'],$u['id'],$name,$cat,$price,$stock,$desc]); $pid=$pdo->lastInsertId();
 $files=$_FILES['images']??null; if($files){$total=min(count($files['name']),MAX_IMAGES_PER_PRODUCT); for($i=0;$i<$total;$i++){ if($files['error'][$i]===UPLOAD_ERR_OK){$single=['name'=>$files['name'][$i],'type'=>$files['type'][$i],'tmp_name'=>$files['tmp_name'][$i],'error'=>$files['error'][$i],'size'=>$files['size'][$i]]; $path=upload_file($single,'uploads/products'); if($path)$pdo->prepare('INSERT INTO product_images(product_id,image_path) VALUES(?,?)')->execute([$pid,$path]);}}}
 header('Location: manage-products.php');exit;
}
?><!DOCTYPE html><html><head><title>Add Product</title><link rel="stylesheet" href="css/styles.css"></head><body><?php include 'includes/header.php'; ?><form class="form-shell" method="post" enctype="multipart/form-data"><h1>Add Product</h1><div class="field"><label>Product Name</label><input name="product_name" required></div><div class="field"><label>Category</label><input name="category" placeholder="Hoodie, Sneaker, Tracksuit" required></div><div class="field"><label>Price</label><input type="number" step="0.01" name="price" required></div><div class="field"><label>Stock Quantity</label><input type="number" name="stock" value="1" required></div><div class="field"><label>Description</label><textarea name="description" required></textarea></div><div class="field"><label>Product Images, maximum 5 per product</label><input type="file" name="images[]" multiple></div><button>Upload Product</button></form></body></html>
